export default class PackageFieldStrings {
    public titles: { [key: string]: string } = {
        "accent": "Akzentfarbe",
        "additionalInfo": "Zusätzliche Informationen",
        "additionalInformationTitle": "Information (Titel)",
        "additionalInformationContent": "Information (Text)",
        "alternativeButtonLine1": "Alternativer Button (Zeile 1)",
        "alternativeButtonLine2": "Alternativer Button (Zeile 2)",
        "availableOnTags": "Verfügbar auf",
        "badgeBackgroundColor": "Abzeichen (Hintergrundfarbe)",
        "badgeContent": "Abzeichen (Text)",
        "badgeForegroundColor": "Abzeichen (Vordergrundfarbe)",
        "badges": "Abzeichen",
        "bundleContentIds": "Bundle-Content (Paket-Ids)",
        "changelogPageName": "Changelog (Seitenname)",
        "coverImageUrl": "Cover-URL",
        "customPageContent": "Inhalt",
        "customPageId": "Id",
        "customPageName": "Name",
        "customPages": "Benutzerdefinierte Seiten",
        "featureList": "Features",
        "fullDescription": "Beschreibung",
        "hasAlternativeButton": "Alternativen Button anzeigen",
        "hasChangelogPage": "Changelog anzeigen",
        "hasPrimaryButton": "Primären Button anzeigen",
        "hasPromo": "Promo anzeigen",
        "hasReviews": "Reviews anzeigen",
        "hasSecondaryButton": "Sekundären Button anzeigen",
        "hasSystemRequirementsPage": "Systemanforderungen anzeigen",
        "iconUrl": "Icon-URL",
        "isAvailable": "Paket freigeben",
        "isPrimaryButtonDisabled": "Primären Button deaktivieren",
        "isPublic": "Paket veröffentlichen",
        "isVisible": "Paket anzeigen",
        "newPrice": "Neuer Preis",
        "oldPrice": "Alter Preis",
        "overviewPageName": "Übersicht (Seitenname)",
        "packageAlias": "Paket-Alias",
        "packageId": "Paket-Id",
        "packageName": "Paketname",
        "packageType": "Paketart",
        "packageType/bundle": "Bundle",
        "packageType/dlc": "DLC",
        "packageType/package": "Paket",
        "priceDetail": "Preisdetails",
        "primaryButtonContent": "Primärer Button (Text)",
        "primaryButtonUrl": "Primärer Button (URL)",
        "projectUrl": "Projekt-URL",
        "promoContent": "Promo (Text)",
        "promoCtaBackgroundColor": "Promo CTA-Button (Hintergrundfarbe)",
        "promoCtaContent": "Promo CTA-Button (Text)",
        "promoCtaForegroundColor": "Promo CTA-Button (Vordergrundfarbe)",
        "promoCtaUrl": "Promo CTA-Button (URL)",
        "promoTitle": "Promo (Überschrift)",
        "requirementKey": "Anforderung (Name)",
        "requirementValue": "Anforderung (Wert)",
        "requirements": "Systemanforderungen",
        "requirementsSubtitle": "Systemanforderungen (Untertitel)",
        "requirementsTitle": "Systemanforderungen (Titel)",
        "reviewsPageName": "Reviews (Seitenname)",
        "screenshots": "Screenshots",
        "secondaryActionContent": "Text",
        "secondaryActionUrl": "URL",
        "secondaryActions": "Sekundäre Aktionen",
        "seperatorContent": "Trenner-Text",
        "shortDescription": "Kurzbeschreibung",
        "systemRequirementsPageName": "Systemanforderungen (Seitenname)",
        "tcsContent": "Hinweise",
        "versionChangelog": "Änderungen",
        "versionName": "Version (Name)",
        "versions": "Versionen",
        "versionTag": "Version (Tag)",
        "versionUrl": "Version (URL)",
    };

    public descriptions: { [key: string]: string } = {
        "primaryButtonUrl": "Überschreibt die aktuelle Versions-URL"
    };
}